name: CastleWars
version: 1.0.0
main: com.fefemf10.castleWars.CastleWars
api-version: '1.21'
depend: [PlayerKits2]
commands:
  cw:
    description: "CastleWars"
    usage: "/cw [create|delete|setkit|spawnpoint|flagpoint|start|stop|connect|leave]"